server:
  port: 9999

spring:
  application:
    name: @artifactId@
#  config:
#    import:
#      - optional:nacos:${spring.application.name}-dev.yml
#      - optional:nacos:${spring.application.name}-@profiles.active@.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        refreshable-dataids: gateway-dev.yml
    gateway:
#      discovery:
#        locator:
#          enabled: true #是否开启从注册中心动态创建路由的功能，可调用RouteConfigController中的接口传递参数
      routes:
        - id: meet-admin-biz    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://meet-admin-biz
          predicates:
            - Path=/**      #断言，路径相匹配的进行路由
          filters:
            - Meet=atguigu
            - Meet=X-Request-atguigu1,atguiguValue1
        - id: meet-auth    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://meet-auth
          predicates:
            - Path=/**      #断言，路径相匹配的进行路由
#        - id: admin_routh    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:9001/   #匹配后提供服务的路由地址（负载均衡该服务名下所有的机器）
#          predicates:
#            - Path=/**      #断言，路径相匹配的进行路由
#          filters:
#            - StripPrefix=1   #重写StripPrefix
#            - After=2022-07-11T19:23:25.599+08:00[Asia/Shanghai]
#        - id: admin_routh2
#          uri: http://localhost:9521
#          uri: lb://meet-admin-biz
#          predicates:
#            - Path=/test/**
##            - After=2022-07-11T19:23:25.599+08:00[Asia/Shanghai] #当前日期在该日期之后才能调用,可调用ZonedDateTime.now()
#            - Cookie=username,zzyy  #curl http://localhost:9527/payment/lb --cookie "username=zzyy"
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb -H "X-Request-Id:123"   多个参数可以在后面追加-H，例如:curl http://192.168.88.190:9999/order/xpmjobcontent/list -H "Authorization:Bearer 9fec3140-b863-4109-85ba-24beed3f2803" -H "TENANT-ID:10"
#            - Host=**.atguigu.com #curl http://localhost:9527/payment/lb -H "Host: www.atguigu.com"
#            - Method=Get #只允许get请求访问  curl http://localhost:9527/payment/lb
#            - Query=username, \d+  #要有参数名username并且值还要是整数才能路由  curl http://localhost:9527/payment/lb?username=111